### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000"
network-passphrase = "Soroban Development Network ; September 2021"

# The rpc-url and network-passphrase are required for all environments.
# Coming soon: If given `run-locally = true`, the `network` will be launched with:
# `stellar network container start local`

[[development.accounts]]
name = "me"
default = true

# You can provide an expanded definition for each account:
#   - `name`: the only required field, an identity with this name will be created
#      with `stellar keys`.
#   - `default`: whether to use this account as the `--source` for commands
#     that need one. Only one default is allowed. The keypair will be generated
#      and saved in the `.soroban/identity` directory.
# Coming Soon: # If you provide just a string, an identity with this name will be created with
# `soroban keys`, which saves the mnemonic in `.soroban/identity`. E.g.: "alice"


[development.contracts]
example-core = { workspace = true }
example-status-message = { workspace = true }

# List each contract individually.
# `workspace = true` indicates that this project is part of the local cargo workspace.
# In dev & test environments, workspace contracts will be automatically built, deployed, initialized, bound, and imported.
# Coming Soon: Auto-build, -deploy, -bind, and -import all contracts in Cargo workspace
# Only supported in development & test environments
# cargo-workspace = true

# Coming Soon: Initialization steps for the contract, to be run after deployment.
# Only supported in `development` and `test` environments.
# You only need to specify the slop (everything after the `--`) for calls to
# `soroban contract invoke` for the given contract. Uses `default-account`
# by default; to use another, prefix with `SOROBAN_ACCOUNT=other-account`.
# init = """
# initialize --symbol ABND --decimal 7 --name abundance --admin me
# mint --amount 2000000 --to me"
# """

# Coming Soon: Specify live contracts to bind & import in this project using the given name.
# During initialization, these contracts will also be "spooned" into the development network,
# meaning that their data will match the live network at the given sequence number.
# [development.contracts.eurc]
# environment = "production"
# address = "C..."
# at-ledger-sequence = 50153603